services:
  # api:
  #   container_name: api
  #   build: ./api
  #   ports:
  #     - 7272:7272
  #   networks:
  #     - payhub
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./backend/golang
  #         target: /app
  #         ignore:
  #           - .env
  #       - action: rebuild
  #         path: go.sum

  postgres:
    container_name: db-payhub
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payhub
    ports:
      - 5887:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - payhub

  redis:
    container_name: cache-payhub
    image: redis:7-alpine
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - payhub

volumes:
  postgres:
  redis:

networks:
  payhub:
