services:
  api:
    container_name: api
    build: ./api
    # environment:
    # - JWT_KEY=${JWT_KEY}
    # - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - 7272:7272
    networks:
      - paymentManager
    develop:
      watch:
        - action: sync
          path: ./backend/golang
          target: /app
          ignore:
            - .env
        - action: rebuild
          path: go.sum

networks:
  paymentManager:
