services:
  client:
    container_name: client
    build: ./client
    ports:
      - 7000:80
    networks:
      - paymentManager
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/share/nginx/html

  api:
    container_name: api
    build: ./api
    environment:
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${GO_API_PORT}:7272
    networks:
      - paymentManager
    develop:
      watch:
        - action: sync
          path: ./backend/golang
          target: /app
          ignore:
            - .env
        - action: rebuild
          path: go.sum

  db:
    container_name: payment-database
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5444
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - paymentManager

volumes:
  postgres:

networks:
  paymentManager:
